openapi: 3.0.3

info:
  title: Glider Insurance
  description: Multi-tenant bridge for insurance providers on Winding Tree marketplace
  contact:
    email: dev@windingtree.com
  license:
    name: GNU GENERAL PUBLIC LICENSE
    url: https://www.gnu.org/licenses/gpl-3.0.html
  version: 1.0.0

servers:
  - url: API_VERSION_URL
    description: API server

tags:
  - name: offers
    description: Search for insurance policies offers
  - name: service
    description: API service functions

paths:
  /offers/search:
    post:
      tags:
        - offers
      summary: Offers Search
      operationId: offersSearch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchCriteria"
      security:
        - orgid_auth:
            - read:offers
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResults"
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        401:
          description: Authorization required
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        403:
          description: Not authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        405:
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /service/ping:
    get:
      tags:
        - service
      summary: Ping-pong
      operationId: servicePing
      parameters:
        - in: query
          name: message
          description: Optional incoming message
          schema:
            type: string
          example: Ping
      security: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"

    post:
      tags:
        - service
      summary: Ping-pong using POST
      operationId: servicePingPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PingRequest"
      security: []
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"

components:
  schemas:
    SearchCriteria:
      description: Insurance policies offers search criteria
      type: object
      required:
        - query
      properties:
        query:
          description: Search query
          type: string
          example: test

    SearchResults:
      description: Array of offers
      type: object
      required:
        - offers
      properties:
        offers:
          type: array
          items:
            $ref: "#/components/schemas/Offer"

    Offer:
      description: Insurance policy offer
      type: object
      properties:
        id:
          $ref: "#/components/schemas/UUID"

    UUID:
      description: Unique identifier for Offers and Orders
      type: string
      format: uuid
      minLength: 36
      maxLength: 36
      pattern: "^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$"
      example: "11111111-2222-3333-4444-000000000001"

    Error:
      description: Object describing an error
      type: object
      required:
        - message
        - code
      properties:
        message:
          description: Error message
          type: string
          example: "Something went wrong"
        code:
          description: Error code
          type: string
          pattern: "^[0-9A-Z]+$"
          example: "BAD_REQUEST"

    PingRequest:
      description: Request options for Ping
      type: object
      required:
        - message
      properties:
        message:
          description: Request message
          type: string
          example: Ping

    Pong:
      description: Pong response object
      type: object
      required:
        - message
      properties:
        message:
          description: Response message
          type: string
          example: Pong
        date:
          description: Current server date
          type: string
          format: date-time
          example: 2021-04-14T23:20:50.52Z

  securitySchemes:
    orgid_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
